name: call_e_log
description: "A Flutter plugin to access and query call history log. Support for Android only as iOS does not provide API for accessing call history."
version: 0.0.4
homepage: https://github.com/Shrikantmurya/call_e

# Remove this line to allow publishing to pub.dev
# publish_to: none  

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies: 
  device_info_plus: ^11.1.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_sound: ^9.16.3
  get: ^4.6.6
  intl: ^0.19.0
  permission_handler: ^11.3.1
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.calllog
        pluginClass: CallLogPlugin
